### ISSUE TITLE
Any update on .net 5?

### ISSUE THREAD

**Issue by gregoryagu** [Breeze/breeze.server.net5#1]
I was spinning up a test project using MVC6 and ASP.net 5, and the thought crossed my mind - "I wonder if Breeze has been updated to support .net5 yet?"

I don't actually need it as 4.5.2 works just fine right now. 

But I would start using it on new projects if it was available, so thought I would ask :)  

(But it's perfectly OK if it's not on the horizon right now.)

Greg Gum

**Comment by marcelgood** [comment]
No not yet. We will get around to it in time, though.
